server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'
  application:
    name: '@project.artifactId@'
  kafka:
    consumer:
      bootstrap-servers: ${kafka.brokers}
      group-id: my_group_demo
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: ${kafka.brokers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    name: myTopic
    partition: 6
    replica: 3
    compressionType: zstd

---
spring:
  config:
    activate:
      on-profile: dev

kafka.brokers: localhost:9092,localhost:9093,localhost:9094,localhost:9095,localhost:9096

---
spring:
  config:
    activate:
      on-profile: beta

kafka.brokers: kafka_1:29092,kafka_2:29093,kafka_3:29094,kafka_4:29095,kafka_5:29096